#index:
#    path: /
#    controller: App\Controller\DefaultController::index
web_controller:
  resource: ../src/Controller/Web/
  type: annotation

rest_controller:
  resource: ../src/Controller/Rest/
  type: annotation
  prefix: /api/v1
